version: '3.8'

services:

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./env
    ports:
      - "${SERVER_PORT_HTTP}:7001"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13
    container_name: db
    env_file:
      - ./env
    environment:
      POSTGRES_DB: sti-jobs
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
