/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JobDTO } from './jobDTO';
import { MachineDTO } from './machineDTO';
import { MachineTypeDTO } from './machineTypeDTO';
import { ScheduleDTO } from './scheduleDTO';

export interface JsonDTO { 
    jobs?: Array<JobDTO>;
    machines?: Array<MachineDTO>;
    machineTypes?: Array<MachineTypeDTO>;
    schedules?: Array<ScheduleDTO>;
}