/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MachineDTO { 
    id?: number;
    name: string;
    description?: string;
    status: MachineDTO.StatusEnum;
    typeId: number;
    createdAt?: Date;
    updatedAt?: Date;
}
export namespace MachineDTO {
    export type StatusEnum = 'AVAILABLE' | 'BUSY' | 'MAINTENANCE' | 'OUT_OF_SERVICE';
    export const StatusEnum = {
        AVAILABLE: 'AVAILABLE' as StatusEnum,
        BUSY: 'BUSY' as StatusEnum,
        MAINTENANCE: 'MAINTENANCE' as StatusEnum,
        OUTOFSERVICE: 'OUT_OF_SERVICE' as StatusEnum
    };
}