/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Machine } from './machine';
import {JobDTO} from "./jobDTO";

export interface MachineType {
    id?: number;
    name?: string;
    description?: string;
    machines?: Array<Machine>;
    jobs?: Array<JobDTO>;
}
